image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

build:
  stage: build
  script:
    gradle assemble

checkStyle:
  stage: staticAnalysis
  script:
    gradle checkstyleMain

PMD:
  stage: staticAnalysis
  script:
    gradle pmdMain

test:
  stage: test
  script:
    gradle test